name: retrain_and_docker

on:
  push:
    branches: [ main ]
    paths: [ 'MLProject/**' ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/demand-forecast:latest
      GDRIVE_FOLDER: ${{ secrets.DRIVE_FOLDER_ID }}


    steps:
    # 1.  Checkout repo
    - uses: actions/checkout@v3

    # 2.  Setup Python 3.12.7
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # 3.  Check Env
    - name: Check Env
      run: |
        python -V
        echo "Runner: $RUNNER_OS $RUNNER_ARCH"

    # 4.  Install dependencies once (pip)
    - name: Install dependencies
      run: |
        pip install -r MLProject/requirements.txt

    # 5.  Run MLflow Project using *local* env  ←  ⏩ TANPA Conda ⏩
    - name: Run mlflow project
      run: |
        cd MLProject
        mlflow run . -P num_boost_round=300 --env-manager=local

    # 6.  Locate latest model artefact
    - name: Get latest MLflow run_id
      id: getrun
      run: |
        RUN_DIR=$(ls -td MLProject/mlruns/*/* | head -n1)
        echo "run_dir=$RUN_DIR" >> $GITHUB_OUTPUT
        echo "model_path=$(find $RUN_DIR/artifacts/model -name '*.json' | head -n1)" >> $GITHUB_OUTPUT
        echo "enc_path=$(find $RUN_DIR/artifacts/model -name '*encoder.pkl' | head -n1)" >> $GITHUB_OUTPUT
   